branches:
  only:
    - Desarrollo
language: php

php:
    - '5.6'

before_script:
    - 'composer install'

script:
    - './vendor/bin/phpunit RecetasPlus/PruebasTest.php'

after_success:
  #- git clone git:repositoryname --branch otherbranch
  #- git checkout -b master
  #- cd RecetasPlus
  #- git config --global user.email "miguel.beltran01@uptc.edu.co"
  #- git config --global user.name "MiguelMike93"
  #- git commit -m "integracion con travis ci"
  #- git checkout -b master
  #- git reset --hard origin/master
  #- git merge origin/Desarrollo -m "Update to deploy"
  #- git remote set-url origin https://$USER:$PASS@github.com/MiguelMike93/PlusRecetas.git
  #- git push origin master
  - git clone https://github.com/MiguelMike93/PlusRecetas.git
  - cd PlusRecetas
  - git config --global user.email $EMAIL
  - git config --global user.name $USER
  - git checkout master
  - git merge origin/Desarrollo -m "Integración3 desde Travis CI"
  - git remote set-url origin https://$USER:$PASS@github.com/MiguelMike93/PlusRecetas.github  
  - git push origin master

notifications:

  email:
    recipients:
    - miguel.beltran01@uptc.edu.co
    on_success: never # default: change
    on_failure: always # default: always
